[tox]
envlist = autopep8, docformatter, docformatter_check, isort, isort_check, pylint, flake8, pydocstyle, codespell, format, lint, docs
skip_missing_interpreters = true

[isort]
line_length = 100
indent = '    '
multi_line_output = 1
length_sort = 1
import_heading_stdlib = std imports
import_heading_thirdparty = 3rd party
import_heading_firstparty = local
import_heading_localfolder = local
sections=FUTURE,STDLIB,TYPING_STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
no_lines_before=LOCALFOLDER
known_first_party = ucs_detect
known_third_party = blessed,wcwidth,yaml,prettytable
known_typing_stdlib = typing,typing_extensions
atomic = true

[flake8]
exclude = .tox,build
max-line-length = 100
ignore = E402,E501,F401,W503,W504

[testenv:autopep8]
basepython = python3.14
deps = autopep8
commands =
    autopep8 \
        --in-place \
        --recursive \
        --aggressive \
        --aggressive \
        --max-line-length 100 \
        ucs_detect/

[testenv:isort]
deps = isort
basepython = python3.13
commands = isort --quiet --apply --recursive ucs_detect

[testenv:pylint]
basepython = python3.13
deps = pylint
commands = pylint --rcfile={toxinidir}/.pylintrc \
           --ignore=docs,conf.py,build,distutils,.pyenv,.git,.tox \
           --ignore-patterns='table_.*\.py,zwj_table\.py' \
           {posargs:{toxinidir}}/ucs_detect

[testenv:flake8]
basepython = python3.13
deps = flake8
commands = flake8 ucs_detect/

[testenv:pydocstyle]
basepython = python3.13
deps = pydocstyle
       doc8
       pygments
commands = pydocstyle --source --explain \
               --match='(?!table_|zwj_table).*\.py' \
               {toxinidir}/ucs_detect
           doc8 --ignore-path docs/_build --ignore D000 --ignore D001 --max-line-length 100 docs

[testenv:docformatter]
basepython = python3.13
deps = docformatter>=1.7.7
       untokenize
commands = - docformatter --in-place --recursive --pre-summary-newline \
             --wrap-summaries=100 --wrap-descriptions=100 \
             {toxinidir}/ucs_detect/

[testenv:docformatter_check]
basepython = python3.13
deps = {[testenv:docformatter]deps}
commands = docformatter --check --diff --recursive --pre-summary-newline \
           --wrap-summaries=100 --wrap-descriptions=100 \
           {toxinidir}/ucs_detect/

[testenv:isort_check]
basepython = python3.13
deps = isort
commands = isort --diff --check-only ucs_detect

[testenv:docs]
basepython = python3.14
deps = -r docs/requirements.txt
commands = {envpython} make_results_rst.py
           sphinx-build -W -d docs/_build/doctrees -b html docs docs/_build/html

[testenv:codespell]
basepython = python3.13
deps = codespell
commands = codespell --skip="*.pyc,htmlcov,_build,build,*.egg-info,.tox,data,*.txt,*.csv,*.ods,*.yaml,typescript" \
                     --ignore-words-list="thirdparty,tham,haa,teh,rin,nd" \
                     --uri-ignore-words-list '*' \
                     --summary --count

[testenv:format]
basepython = python3.13
deps = {[testenv:isort]deps}
       {[testenv:docformatter]deps}
       {[testenv:autopep8]deps}
commands = {[testenv:isort]commands}
           {[testenv:docformatter]commands}
           {[testenv:autopep8]commands}

[testenv:lint]
basepython = python3.13
deps = {[testenv:flake8]deps}
       {[testenv:isort_check]deps}
       {[testenv:pydocstyle]deps}
       {[testenv:pylint]deps}
       {[testenv:codespell]deps}
commands = {[testenv:flake8]commands}
           {[testenv:isort_check]commands}
           {[testenv:pydocstyle]commands}
           {[testenv:pylint]commands}
           {[testenv:codespell]commands}
