[tox]
envlist = autopep8, docformatter, docformatter_check, isort, isort_check, pylint, pylint_tests, flake8, flake8_tests, pydocstyle, codespell, format, lint, docs, py{38, 39, 310, 311, 312, 313, 314}
skip_missing_interpreters = true

[testenv]
deps = -r requirements-tests.txt
commands = {envpython} -m pytest --cov-config={toxinidir}/tox.ini {posargs:\
             --verbose \
             --junit-xml=.tox/results.{envname}.xml \
             --durations=3 \
             } \
          --log-format='%(levelname)s %(relativeCreated)2.2f %(filename)s:%(lineno)d %(message)s' \
          tests
passenv = TEST_QUICK

[isort]
line_length = 100
indent = '    '
multi_line_output = 1
length_sort = 1
import_heading_stdlib = std imports
import_heading_thirdparty = 3rd party
import_heading_firstparty = local
import_heading_localfolder = local
sections=FUTURE,STDLIB,TYPING_STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
no_lines_before=LOCALFOLDER
known_first_party = ucs_detect
known_third_party = blessed,wcwidth,yaml,prettytable
known_typing_stdlib = typing,typing_extensions
atomic = true

[pytest]
norecursedirs = .git .tox build
addopts = --disable-pytest-warnings
          --cov-append --cov-report=html --color=yes --ignore=.tox
          --cov=ucs_detect
filterwarnings =
    error
junit_family = xunit1

[flake8]
exclude = .tox,build
max-line-length = 100
ignore = E402,E501,F401,W503,W504

[coverage:run]
branch = True
source = ucs_detect
parallel = True
relative_files = True

[coverage:report]
omit = tests/*
exclude_lines = pragma: no cover
precision = 1

[coverage:paths]
source = ucs_detect/

[testenv:autopep8]
basepython = python3.14
deps = autopep8
commands =
    autopep8 \
        --in-place \
        --recursive \
        --aggressive \
        --aggressive \
        --max-line-length 100 \
        ucs_detect/ tests/

[testenv:isort]
deps = isort
basepython = python3.13
commands = isort --quiet --apply --recursive ucs_detect tests

[testenv:pylint]
basepython = python3.13
deps = pylint
commands = pylint --rcfile={toxinidir}/.pylintrc \
           --ignore=tests,docs,conf.py,build,distutils,.pyenv,.git,.tox \
           {posargs:{toxinidir}}/ucs_detect

[testenv:flake8]
basepython = python3.13
deps = flake8
commands = flake8 --exclude=tests ucs_detect/ tests/

[testenv:pydocstyle]
basepython = python3.13
deps = pydocstyle
       doc8
       pygments
commands = pydocstyle --source --explain {toxinidir}/ucs_detect
           doc8 --ignore-path docs/_build --ignore D000 --max-line-length 100 docs

[testenv:docformatter]
basepython = python3.13
deps = docformatter>=1.7.7
       untokenize
commands = - docformatter --in-place --recursive --pre-summary-newline \
             --wrap-summaries=100 --wrap-descriptions=100 \
             {toxinidir}/ucs_detect/ {toxinidir}/tests/

[testenv:docformatter_check]
basepython = python3.13
deps = {[testenv:docformatter]deps}
commands = docformatter --check --diff --recursive --pre-summary-newline \
           --wrap-summaries=100 --wrap-descriptions=100 \
           {toxinidir}/ucs_detect/ {toxinidir}/tests/

[testenv:isort_check]
basepython = python3.13
deps = isort
commands = isort --diff --check-only ucs_detect tests

[testenv:flake8_tests]
basepython = python3.13
deps = flake8
commands = flake8 --ignore=E501,W504,F401 tests/

[testenv:pylint_tests]
basepython = python3.13
deps = pytest
       pylint
commands = pylint --rcfile={toxinidir}/.pylintrc \
           --disable=protected-access,unused-argument,missing-function-docstring,line-too-long \
           tests

[testenv:docs]
basepython = python3.14
deps = -r docs/requirements.txt
commands = {envpython} make_results_rst.py
           sphinx-build -W -d docs/_build/doctrees -b html docs docs/_build/html

[testenv:codespell]
basepython = python3.13
deps = codespell
commands = codespell --skip="*.pyc,htmlcov,_build,build,*.egg-info,.tox,data,*.txt,*.csv,*.ods" \
                     --ignore-words-list="thirdparty" \
                     --uri-ignore-words-list '*' \
                     --summary --count

[testenv:format]
basepython = python3.13
deps = {[testenv:isort]deps}
       {[testenv:docformatter]deps}
       {[testenv:autopep8]deps}
commands = {[testenv:isort]commands}
           {[testenv:docformatter]commands}
           {[testenv:autopep8]commands}

[testenv:lint]
basepython = python3.13
deps = {[testenv:flake8]deps}
       {[testenv:isort_check]deps}
       {[testenv:pydocstyle]deps}
       {[testenv:pylint_tests]deps}
       {[testenv:codespell]deps}
commands = {[testenv:flake8]commands}
           {[testenv:flake8_tests]commands}
           {[testenv:isort_check]commands}
           {[testenv:pydocstyle]commands}
           {[testenv:pylint]commands}
           {[testenv:pylint_tests]commands}
           {[testenv:codespell]commands}
