"""Generate contested codepoint/grapheme tables from data/*.yaml failures.

Scans all terminal data YAMLs, collects every codepoint and grapheme that has
ever failed (measured_by_terminal != measured_by_wcwidth) in any terminal, and
generates Python modules containing only those contested entries.

Output modules use the same format as the full table modules, so they can be
used as drop-in replacements.

Usage::

    python scripts/make_contested_tables.py
"""
# std imports
import glob
import os
import textwrap
import collections
import sys

try:
    from yaml import CSafeLoader as SafeLoader
except ImportError:
    from yaml import SafeLoader

import yaml

_HERE = os.path.dirname(os.path.abspath(__file__))
_PROJECT = os.path.dirname(_HERE)
_DATA_DIR = os.path.join(_PROJECT, 'data')
_OUT_DIR = os.path.join(_PROJECT, 'ucs_detect')

HEADER = '# -*- coding: utf-8 -*-\n# Auto-generated by scripts/make_contested_tables.py\n'


def _wchars_to_ints(wchars_str):
    """Decode a \\uXXXX or \\UXXXXXXXX escape string to tuple of ints."""
    decoded = wchars_str.encode('ascii').decode('unicode_escape')
    return tuple(ord(ch) for ch in decoded)


def _parse_single_codepoint(wchar_str):
    """Parse a wchar string, stripping trailing VS15/VS16, returning the base codepoint int."""
    decoded = wchar_str.encode('ascii').decode('unicode_escape')
    if len(decoded) > 1 and decoded[-1] in ('\ufe0f', '\ufe0e'):
        return ord(decoded[0])
    return ord(decoded)


def _grapheme_id_width(grapheme_id):
    """Extract width from a grapheme_id like 'Bengali-4-00'."""
    parts = grapheme_id.split('-')
    if len(parts) >= 2:
        try:
            return int(parts[1])
        except ValueError:
            return None
    return None


def collect_failures():
    """Collect all unique failures from data/*.yaml, grouped by category."""
    # WIDE, SRI, SFZ: set of int (base codepoint)
    wide_set = set()
    sri_set = set()
    sfz_set = set()

    # VS16, VS15, ZWJ, RI: set of tuple-of-ints (sequence)
    vs16_set = set()
    vs15_set = set()
    zwj_set = set()
    ri_set = set()

    # LANG: dict of language -> set of (width, grapheme_string)
    lang_by_width = collections.defaultdict(lambda: collections.defaultdict(set))

    yaml_files = sorted(glob.glob(os.path.join(_DATA_DIR, '*.yaml')))
    for yaml_path in yaml_files:
        with open(yaml_path, encoding='utf-8') as f:
            doc = yaml.load(f, Loader=SafeLoader)
        test_results = doc.get('test_results', {})

        for yaml_key, target_set in (
                ('unicode_wide_results', wide_set),
                ('sri_results', sri_set),
                ('sfz_results', sfz_set)):
            cat_data = test_results.get(yaml_key, {})
            for _ver, ver_data in cat_data.items():
                for entry in ver_data.get('failed_codepoints', []):
                    if 'inherited_from' in entry:
                        continue
                    target_set.add(
                        _parse_single_codepoint(entry['wchar']))

        for yaml_key, target_set in (
                ('emoji_vs16_results', vs16_set),
                ('emoji_vs15_results', vs15_set),
                ('emoji_zwj_results', zwj_set),
                ('ri_results', ri_set)):
            cat_data = test_results.get(yaml_key, {})
            for _ver, ver_data in cat_data.items():
                for entry in ver_data.get('failed_codepoints', []):
                    if 'inherited_from' in entry:
                        continue
                    wchar_str = entry.get('wchar') or entry.get('wchars')
                    seq = _wchars_to_ints(wchar_str)
                    if len(seq) >= 2:
                        target_set.add(seq)

        lang_data = test_results.get('language_results') or {}
        for lang_name, lang_entry in lang_data.items():
            if lang_entry is None:
                continue
            for entry in lang_entry.get('failed', []):
                if 'inherited_from' in entry:
                    continue
                grapheme_id = entry.get('grapheme_id', '')
                width = _grapheme_id_width(grapheme_id)
                if width is None:
                    width = entry.get('measured_by_wcwidth', 1)
                grapheme_str = entry['wchars'].encode('ascii').decode('unicode_escape')
                lang_by_width[width][lang_name].add(grapheme_str)

    return {
        'wide': wide_set,
        'sri': sri_set,
        'sfz': sfz_set,
        'vs16': vs16_set,
        'vs15': vs15_set,
        'zwj': zwj_set,
        'ri': ri_set,
        'lang': lang_by_width,
    }


def _write_single_cp_table(out_path, var_name, cp_set, version):
    """Write a single-codepoint contested table module."""
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        if not cp_set:
            f.write(f'\n{var_name} = ()\n')
            return
        f.write(f'\n{var_name} = (\n')
        f.write(f"    ({version!r}, (\n")
        line_parts = []
        for cp in sorted(cp_set):
            line_parts.append(str(cp))
        line = ', '.join(line_parts)
        for wrapped in textwrap.wrap(line, width=88, break_on_hyphens=False):
            f.write(f'        {wrapped}\n')
        f.write('    )),\n')
        f.write(')\n')


def _write_sequence_table(out_path, var_name, seq_set, version):
    """Write a sequence (tuple-of-ints) contested table module."""
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        if not seq_set:
            f.write(f'\n{var_name} = ()\n')
            return
        f.write(f'\n{var_name} = (\n')
        f.write(f"    ({version!r}, (\n")
        for seq in sorted(seq_set):
            parts = ", ".join(str(cp) for cp in seq)
            if len(seq) == 1:
                parts += ","
            f.write(f'        ({parts}),\n')
        f.write('    )),\n')
        f.write(')\n')


def _write_lang_table(out_path, var_name, lang_by_width):
    """Write a language grapheme contested table module."""
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        if not lang_by_width:
            f.write(f'\n{var_name} = ()\n')
            return
        f.write(f'\n{var_name} = (\n')
        for width in sorted(lang_by_width, reverse=True):
            lang_dict = lang_by_width[width]
            f.write(f'    ({width}, (\n')
            for lang in sorted(lang_dict):
                graphemes = sorted(lang_dict[lang])
                f.write(f'        ({lang!r}, (\n')
                for g in graphemes:
                    f.write(f'            {g!r},\n')
                f.write('        )),\n')
            f.write('    )),\n')
        f.write(')\n')


def main():
    """Generate all contested table modules."""
    failures = collect_failures()

    _write_single_cp_table(
        os.path.join(_OUT_DIR, 'table_wide_contested.py'),
        'WIDE_CONTESTED', failures['wide'], '17.0.0')
    _write_single_cp_table(
        os.path.join(_OUT_DIR, 'table_sri_contested.py'),
        'SRI_CONTESTED', failures['sri'], '17.0.0')
    _write_single_cp_table(
        os.path.join(_OUT_DIR, 'table_sfz_contested.py'),
        'SFZ_CONTESTED', failures['sfz'], '17.0.0')
    _write_sequence_table(
        os.path.join(_OUT_DIR, 'table_vs16_contested.py'),
        'VS16_CONTESTED', failures['vs16'], '17.0.0')
    _write_sequence_table(
        os.path.join(_OUT_DIR, 'table_vs15_contested.py'),
        'VS15_CONTESTED', failures['vs15'], '17.0.0')
    _write_sequence_table(
        os.path.join(_OUT_DIR, 'table_zwj_contested.py'),
        'ZWJ_CONTESTED', failures['zwj'], '17.0.0')
    _write_sequence_table(
        os.path.join(_OUT_DIR, 'table_ri_contested.py'),
        'RI_CONTESTED', failures['ri'], '17.0.0')
    _write_lang_table(
        os.path.join(_OUT_DIR, 'table_lang_contested.py'),
        'LANG_CONTESTED', failures['lang'])

    counts = {k: len(v) for k, v in failures.items() if k != 'lang'}
    lang_count = sum(
        len(graphemes)
        for width_dict in failures['lang'].values()
        for graphemes in width_dict.values()
    )
    counts['lang'] = lang_count

    print(f"Generated contested tables: {counts}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
