"""Generate the tofu (font glyph coverage) codepoint table for ucs_detect."""
import os
import re

import wcwidth

from ucs_detect.accessories import do_retrieve, get_data_dir

URL_UCD = "https://www.unicode.org/Public/UCD/latest/ucd/{filename}"
PATH_DATA = str(get_data_dir())

# General categories whose codepoints can never be a tofu: controls, format
# characters, surrogates, private use, and unassigned.
SKIP_CATEGORIES = frozenset(('Cc', 'Cf', 'Cs', 'Co', 'Cn'))


def _retrieve(filename):
    """Retrieve *filename* from the UCD into ``data/``, return its path."""
    fname = os.path.join(PATH_DATA, filename.replace('.txt', '-latest.txt'))
    do_retrieve(url=URL_UCD.format(filename=filename), fname=fname)
    return fname


def fetch_categories():
    """Map every assigned codepoint to its general category."""
    categories = {}
    range_start = None
    with open(_retrieve('UnicodeData.txt'), encoding='utf-8') as fin:
        for line in fin:
            fields = line.split(';')
            if len(fields) < 3:
                continue
            codepoint, name, category = int(fields[0], 16), fields[1], fields[2]
            if name.endswith(', First>'):
                range_start = codepoint
                continue
            if name.endswith(', Last>') and range_start is not None:
                for cp in range(range_start, codepoint + 1):
                    categories[cp] = category
                range_start = None
                continue
            categories[codepoint] = category
    return categories


def fetch_default_ignorable():
    """Return the set of Default_Ignorable_Code_Point codepoints."""
    pattern = re.compile(
        r'^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*'
        r'Default_Ignorable_Code_Point\s*#')
    ignorable = set()
    with open(_retrieve('DerivedCoreProperties.txt'), encoding='utf-8') as fin:
        for line in fin:
            match = pattern.match(line)
            if match:
                start = int(match.group(1), 16)
                end = int(match.group(2) or match.group(1), 16)
                ignorable.update(range(start, end + 1))
    return ignorable


def fetch_blocks():
    """Return a list of ``(start, end, block_name)`` for all Unicode blocks."""
    pattern = re.compile(r'^([0-9A-F]{4,6})\.\.([0-9A-F]{4,6});\s*(.+?)\s*$')
    blocks = []
    with open(_retrieve('Blocks.txt'), encoding='utf-8') as fin:
        for line in fin:
            match = pattern.match(line)
            if match:
                blocks.append((int(match.group(1), 16),
                               int(match.group(2), 16),
                               match.group(3)))
    return blocks


def fetch_tofu_data():
    """Return ``[(version, [(start, end, block_name), ...])]`` of testable codepoints."""
    version = wcwidth.list_versions()[-1]
    categories = fetch_categories()
    ignorable = fetch_default_ignorable()

    ranges = []
    for block_start, block_end, block_name in fetch_blocks():
        run_start = None
        for codepoint in range(block_start, block_end + 1):
            category = categories.get(codepoint)
            drawable = (category is not None
                        and category not in SKIP_CATEGORIES
                        and codepoint not in ignorable
                        and wcwidth.wcwidth(chr(codepoint)) > 0)
            if drawable:
                if run_start is None:
                    run_start = codepoint
            elif run_start is not None:
                ranges.append((run_start, codepoint - 1, block_name))
                run_start = None
        if run_start is not None:
            ranges.append((run_start, block_end, block_name))
    return [(version, ranges)]


def main():
    """Generate and write the tofu unicode table module."""
    print('"""Assigned, drawable codepoints tested for missing font glyphs (tofus)."""')
    print("# Generated by scripts/make_tofu_table.py -- do not edit.")
    print("TOFU_CODEPOINTS = (")
    for key, ranges in fetch_tofu_data():
        print(f"    ('{key}', (")
        for start, end, block_name in ranges:
            escaped = block_name.replace("'", "\\'")
            print(f"        (0x{start:04X}, 0x{end:04X}, '{escaped}'),")
        print("    )),")
    print(")")


if __name__ == "__main__":
    # $ python scripts/make_tofu_table.py > ucs_detect/table_tofu.py
    main()
